dataset:
  type: single_knn
  params:
    base: two_moons
    n_samples: 100
    noise: 0.15
    lam: 1.0
  validation:
    use_train: True
model_config:
  model: EncodeProcessDecode
  cfg:
    processor_cfg:
      model: GNNBaseline
      cfg:
        layer_type: GATConv
        hidden_dim: 128
        num_layers: 2
        tau: 0.35
        sigma: 0.35
    in_node_dim: 2
    in_edge_dim: 2
    embedding_dim: 32
    mlp_hidden_dim: 128
    lam: 2.0
    residual_stream: False
    recurrent_steps: 1
device: cuda:4
epochs: 500
loss_function: energy
lr: 0.0001
batch_size: 1

