dataset:
  type: gaussian_sbm_dataset
  params:
    n_graphs: 1
    n_nodes: 200
    n_clusters: 2
    p_in: 0.10
    p_out: 0.001
    feature_dim: 2
    seed: 42
  validation:
    use_train: False
model_config:
  model: EncodeProcessDecode
  cfg:
    processor_cfg:
      model: GraphPDHGNet
      cfg:
        layer_type: PDHGLayer
        hidden_dim: 128
        num_layers: 8
        tau: 0.35
        sigma: 0.35
    in_node_dim: 2
    in_edge_dim: 2
    embedding_dim: 32
    mlp_hidden_dim: 128
    lam: 0.0
    residual_stream: False
    recurrent_steps: 1
device: cuda:6
epochs: 1000
loss_function: energy_pdg
lr: 0.0001
batch_size: 1

