dataset:
  type: gaussian_sbm_dataset
  params:
    n_graphs: 1000
    n_nodes: 200
    n_clusters: 5
    p_in: 0.10
    feature_dim: 16
    seed: 42
  validation:
    use_train: False
model_config:
  model: EncodeProcessDecode
  cfg:
    processor_cfg:
      model: GraphPDHGNet
      cfg:
        layer_type: PDHGLayer
        hidden_dim: 128
        num_layers: 4
        tau: 0.35
        sigma: 0.35
    in_node_dim: 2
    in_edge_dim: 2
    embedding_dim: 32
    mlp_hidden_dim: 128
    lam: 1.0
    residual_stream: True
    recurrent_steps: 1
device: cuda:0
epochs: 500
loss_function: energy_pdg
lr: 0.0001
batch_size: 1

