dataset:
  type: gaussian_sbm_dataset
  params:
    n_graphs: 100
    n_nodes: 200
    n_clusters: 5
    p_in: 0.10
    feature_dim: 16
    seed: 42
  validation:
    use_train: True
model_config:
  model: GraphPDHGNet
  cfg:
    layer_type: PDHGLayer 
    in_node_dim: 16
    in_edge_dim: 16
    hidden_dim: 128
    num_layers: 4
    lam: 1.0
    tau: 0.35
    sigma: 0.35
device: cuda:0
epochs: 100
loss_function: energy_pdg
lr: 0.0001
batch_size: 1

