lam: 1.0
iters: 500
tau: 0.35
sigma: 0.35
dataset_pth: /data/sam/primal-dual/data/multiple_knn_base=two_moons_n_samples=200_n_graphs=100_noise=0.15-train.pt
savepth: /data/sam/primal-dual/data/multiple_knn_base=two_moons_n_samples=200_n_graphs=100_noise=0.15-train.pt_lam=1.0