lam: 1.0
iters: 500
tau: 0.35
sigma: 0.35
dataset_pth: /data/sam/primal-dual/data/gaussian_blob_dataset_n_graphs=1_min_n_nodes=100_max_n_nodes=200_n_clusters=6_k_neighbors=10_feature_dim=2-val.pt
savepth: /data/sam/primal-dual/baselines/gaussian_blob_dataset_n_graphs=1_min_n_nodes=100_max_n_nodes=200_n_clusters=6_k_neighbors=10_feature_dim=2-val_lam=1.0